### ISSUE TITLE
求博客源码分享

### ISSUE THREAD

**Issue by maya1900** [alexwjj/alexwjj.github.io#69]
我也想整一个博客搭在github上，希望分享下源码，感谢

**Comment by hyouka-oasis** [comment]
你看到就是源码呀

**Comment by hyouka-oasis** [comment]
你可以加他微信的，博客点进去有他微信的 @ @

**Comment by hyouka-oasis** [comment]
https://alexwjj.github.io/views/fe/deploy/vue_deploy.html @maya1900

**Comment by maya1900** [comment]
> https://alexwjj.github.io/views/fe/deploy/vue_deploy.html @maya1900

十分感谢，现在就动手！！！

**Comment by maya1900** [comment]
> https://alexwjj.github.io/views/fe/deploy/vue_deploy.html @maya1900

十分感谢，现在就动手！！@HyoukaM
